version: "3.7"

services:
  # This service runs the postgres DB used by dagster for run storage, schedule storage,
  # and event log storage.
  postgresql:
    image: postgres:11
    container_name: docker_example_postgresql
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
    ports:
      - 5432:5432
    networks:
      - docker_example_network

  web_ui:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    container_name: web_ui
    expose:
      - "3000"
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DAGSTER_PG_USERNAME: "postgres_user"
      DAGSTER_PG_PASSWORD: "postgres_password"
      DAGSTER_PG_DB: "postgres_db"
      DAGSTER_PG_HOST: postgresql
      DAGSTER_DBT_PARSE_PROJECT_ON_LOAD: 1

    volumes: # Make docker client accessible so we can terminate containers from dagit
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker_example_network
    depends_on:
      - postgresql

  dagster_daemon:
      build:
        context: .
        dockerfile: ./Dockerfile_dagster
      entrypoint:
        - dagster-daemon
        - run
      container_name: dagster_daemon
      restart: on-failure
      env_file:
        - .env
      environment:
        DAGSTER_PG_USERNAME: "postgres_user"
        DAGSTER_PG_PASSWORD: "postgres_password"
        DAGSTER_PG_DB: "postgres_db"
        DAGSTER_PG_HOST: postgresql
        DAGSTER_DBT_PARSE_PROJECT_ON_LOAD: 1
      volumes: # Make docker client accessible so we can launch containers using host docker
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        - docker_example_network
      depends_on:
        - postgresql

  dagster_grpc_server:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    env_file:
      - .env
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
      DAGSTER_PG_USERNAME: "postgres_user"
      DAGSTER_PG_PASSWORD: "postgres_password"
      DAGSTER_PG_DB: "postgres_db"
      DAGSTER_PG_HOST: postgresql
      DAGSTER_DBT_PARSE_PROJECT_ON_LOAD: 1
    volumes:
      - /Users/tomaspeluritis/dagster_rabbit_hole/dagster-demo:/opt/dagster/dagster_home/dagster-demo
      - /Users/tomaspeluritis/dagster_rabbit_hole/dwh:/opt/dagster/dagster_home/dwh
      - /Users/tomaspeluritis/dagster_rabbit_hole/profiles.yml:/opt/dagster/dagster_home/profiles.yml
    ports:
      - 4266:4266
    networks:
      - docker_example_network
    command: dagster code-server start --module-name dagster-demo -h 0.0.0.0 -p 4266
    restart: unless-stopped

networks:
  docker_example_network:
    driver: bridge
    name: docker_example_network
