FROM python:3.11-slim

RUN mkdir -p /opt/dagster/dagster_home

ENV DAGSTER_HOME=/opt/dagster/dagster_home/

COPY dagster.yaml workspace.yaml $DAGSTER_HOME

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

WORKDIR $DAGSTER_HOME
