dwh:
  target: dev
  outputs:
    dev:
      type: snowflake
      account:  "{{ env_var('SNOWFLAKE_ACCOUNT') }}"

      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DB') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WH') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      threads: 5
      client_session_keep_alive: False
